install:
	pip install -r requirements.txt

run:
	python -m scripts.run_final_graph --question "$(QUESTION)"

swarm:
	python -m scripts.run_swarm_demo --question "$(QUESTION)"

eval:
	python -m scripts.run_evals --mode $(MODE)
